version: '3.8'

services:
  client:
    container_name: idd-client
    build:
      context: ./Client
      dockerfile: Dockerfile
    networks:
      - openresty_network
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge

  openresty_network:
    external: true 
