name: Build and Run Blazor App in Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker
      uses: docker/setup-qemu-action@v2

    - name: Build Docker Image
      run: |
        COMMIT_HASH=$(git rev-parse --short HEAD)    
        docker build -t blazor-app:${COMMIT_HASH} .

    - name: Run Docker Container
      run: |
        COMMIT_HASH=$(git rev-parse --short HEAD)
        docker run -d --network openresty_network -p 8080:80 blazor-app:${COMMIT_HASH}